name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  run-javascript-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node HelloWorld.js
  first-interaction:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACTIONS_TOKEN }}
        issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
        pr-message: "Message that will be displayed on users' first pr. Look, a `code block` for markdown."
